name: build_lmi_system_full
on: 
  workflow_dispatch:
    inputs:
      URL:
        description: '待操作的系统包下载地址'     
        required: true
        default: 'https://bigota.d.miui.com/22.7.7/miui_PSYCHEPRE_22.7.7_a83dac045c_12.0.zip'
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
       - uses: actions/checkout@master  
       - name: 1.安装依赖
         run: |
            sudo apt install python3 python3-pip aria2 zip p7zip-full
            sudo apt --fix-broken install
            sudo apt update --fix-missing
            pip3 install --upgrade pip
            pip3 install pycryptodome
            pip3 install docopt
            pip3 install requests
            pip3 install beautifulsoup4
            pip3 install --ignore-installed pyyaml
       - name: 2.下载系统包
         run: |
            aria2c -x16 -j$(nproc) -U "Mozilla/5.0" -d "$GITHUB_WORKSPACE" ${{ github.event.inputs.URL }}
            aria2c -x16 -j$(nproc) -U "Mozilla/5.0" -d "$GITHUB_WORKSPACE" https://bigota.d.miui.com/22.7.7/miui_LMIPRE_22.7.7_25f68fde92_12.0.zip
       - name: 3.解包
         run: |
            sudo chmod 777 "$GITHUB_WORKSPACE"/tools/payload-dumper-go
            sudo chmod 777 "$GITHUB_WORKSPACE"/tools/brotli
            mkdir -p "$GITHUB_WORKSPACE"/PSYCHE
            mkdir -p "$GITHUB_WORKSPACE"/LMI
            mkdir -p "$GITHUB_WORKSPACE"/images
            mkdir -p "$GITHUB_WORKSPACE"/simages
            mkdir -p "$GITHUB_WORKSPACE"/zip
            mkdir -p "$GITHUB_WORKSPACE"/firmware
            URL=${{ github.event.inputs.URL }}
            ZIP_NAME_PSYCHE=${URL##*/}
            7z x "$GITHUB_WORKSPACE"/$ZIP_NAME_PSYCHE -r -o"$GITHUB_WORKSPACE"/PSYCHE
            rm -rf "$GITHUB_WORKSPACE"/$ZIP_NAME_PSYCHE
            ZIP_NAME_LMI=miui_LMIPRE_22.7.7_25f68fde92_12.0.zip
            7z x "$GITHUB_WORKSPACE"/$ZIP_NAME_LMI -r -o"$GITHUB_WORKSPACE"/LMI firmware-update
            7z x "$GITHUB_WORKSPACE"/$ZIP_NAME_LMI -r -o"$GITHUB_WORKSPACE"/LMI boot.img
            for i in odm vendor
            do
                7z x "$GITHUB_WORKSPACE"/$ZIP_NAME_LMI -o"$GITHUB_WORKSPACE"/LMI $i.transfer.list
                7z x "$GITHUB_WORKSPACE"/$ZIP_NAME_LMI -o"$GITHUB_WORKSPACE"/LMI $i.patch.dat
                7z x "$GITHUB_WORKSPACE"/$ZIP_NAME_LMI -o"$GITHUB_WORKSPACE"/LMI $i.new.dat.br
            done
            "$GITHUB_WORKSPACE"/tools/brotli -d "$GITHUB_WORKSPACE"/LMI/vendor.new.dat.br
            rm -rf "$GITHUB_WORKSPACE"/LMI/vendor.new.dat.br
            python3 "$GITHUB_WORKSPACE"/tools/sdat2img.py "$GITHUB_WORKSPACE"/LMI/vendor.transfer.list "$GITHUB_WORKSPACE"/LMI/vendor.new.dat "$GITHUB_WORKSPACE"/LMI/vendor.img
            rm -rf "$GITHUB_WORKSPACE"/LMI/vendor.patch.dat
            rm -rf "$GITHUB_WORKSPACE"/LMI/vendor.transfer.list
            rm -rf "$GITHUB_WORKSPACE"/LMI/vendor.new.dat
            sudo python3 "$GITHUB_WORKSPACE"/tools/imgextractorLinux.py "$GITHUB_WORKSPACE"/LMI/vendor.img "$GITHUB_WORKSPACE"/LMI
            rm -rf "$GITHUB_WORKSPACE"/LMI/vendor.img
            for i in system product system_ext
            do
                "$GITHUB_WORKSPACE"/tools/payload-dumper-go -p $i "$GITHUB_WORKSPACE"/PSYCHE/payload.bin
                mv "$GITHUB_WORKSPACE"/payload/$i.img "$GITHUB_WORKSPACE"/images/$i.img
            done
            rm -rf "$GITHUB_WORKSPACE"/payload
            rm -rf "$GITHUB_WORKSPACE"/PSYCHE
            sudo python3 "$GITHUB_WORKSPACE"/tools/imgextractorLinux.py "$GITHUB_WORKSPACE"/images/product.img "$GITHUB_WORKSPACE"/images
            rm -rf "$GITHUB_WORKSPACE"/images/product.img
       - name: 4.替换相关文件
         run: |
            sudo rm -rf "$GITHUB_WORKSPACE"/images/product/etc/device_features/*
            sudo rm -rf "$GITHUB_WORKSPACE"/images/product/overlay/DeviceAndroidConfig.apk
            sudo rm -rf "$GITHUB_WORKSPACE"/images/product/overlay/DeviceConfig.apk
            sudo cp -f "$GITHUB_WORKSPACE"/AospFrameworkResOverlay.apk "$GITHUB_WORKSPACE"/images/product/overlay/
            sudo cp -f "$GITHUB_WORKSPACE"/DevicesAndroidOverlay.apk "$GITHUB_WORKSPACE"/images/product/overlay/
            sudo cp -f "$GITHUB_WORKSPACE"/DevicesOverlay.apk "$GITHUB_WORKSPACE"/images/product/overlay/
            sudo cp -f "$GITHUB_WORKSPACE"/lmi.xml "$GITHUB_WORKSPACE"/images/product/etc/device_features/
            sudo cp -f "$GITHUB_WORKSPACE"/lmipro.xml "$GITHUB_WORKSPACE"/images/product/etc/device_features/
            sudo sed -i "s/ro.miui.notch=1/ro.miui.notch=0/g" "$GITHUB_WORKSPACE"/images/product/etc/build.prop
            sudo rm -rf "$GITHUB_WORKSPACE"/LMI/vendor/recovery-from-boot.p
            sudo rm -rf "$GITHUB_WORKSPACE"/LMI/vendor/bin/install-recovery.sh
            sudo mv -f "$GITHUB_WORKSPACE"/vbmeta.img "$GITHUB_WORKSPACE"/LMI/firmware-update
            sudo mv -f "$GITHUB_WORKSPACE"/vbmeta_system.img "$GITHUB_WORKSPACE"/LMI/firmware-update
            sudo cp -r "$GITHUB_WORKSPACE"/LMI/firmware-update "$GITHUB_WORKSPACE"/images
            sudo cp -f "$GITHUB_WORKSPACE"/LMI/boot.img "$GITHUB_WORKSPACE"/images
            sudo cp -r "$GITHUB_WORKSPACE"/META-INF "$GITHUB_WORKSPACE"/images
            sudo cp -f "$GITHUB_WORKSPACE"/dynamic_partitions_op_list "$GITHUB_WORKSPACE"/images
            sudo cp -r "$GITHUB_WORKSPACE"/LMI/* "$GITHUB_WORKSPACE"/images
            sudo rm -rf "$GITHUB_WORKSPACE"/LMI
       - name: 5.打包
         run: |
            sudo chmod 777 "$GITHUB_WORKSPACE"/tools/mke2fs
            sudo chmod 777 "$GITHUB_WORKSPACE"/tools/e2fsdroid
            sudo chmod 777 "$GITHUB_WORKSPACE"/tools/img2simg
            sudo chmod 777 "$GITHUB_WORKSPACE"/tools/brotli
            URL=${{ github.event.inputs.URL }}
            DATE=${URL%/*}
            date=${DATE##*/}
            product_size=$(sudo du -sb "$GITHUB_WORKSPACE"/images/product | awk {'print $1'})
            product_size=$(echo "$product_size + 52428800" | bc)
            product_size=$(echo "$product_size / 4096" | bc)
            vendor_size=$(sudo du -sb "$GITHUB_WORKSPACE"/images/vendor | awk {'print $1'})
            vendor_size=$(echo "$vendor_size + 52428800" | bc)
            vendor_size=$(echo "$vendor_size / 4096" | bc)
            system_size=$(sudo du -sb "$GITHUB_WORKSPACE"/images/system.img | awk {'print $1'})
            system_ext_size=$(sudo du -sb "$GITHUB_WORKSPACE"/images/system_ext.img | awk {'print $1'})
            UTC=$(date -u +%s)
            for i in product vendor
            do
                sudo python3 "$GITHUB_WORKSPACE"/tools/fspatch.py "$GITHUB_WORKSPACE"/images/$i "$GITHUB_WORKSPACE"/images/TI_config/"$i"_fs_config
                "$GITHUB_WORKSPACE"/tools/mke2fs -O ^has_journal -L $i -I 256 -M /$i -m 0 -t ext4 -b 4096 "$GITHUB_WORKSPACE"/images/$i.img $(eval echo "$"$i"_size")
                sudo "$GITHUB_WORKSPACE"/tools/e2fsdroid -e -T $UTC -C "$GITHUB_WORKSPACE"/images/TI_config/"$i"_fs_config -S "$GITHUB_WORKSPACE"/images/TI_config/"$i"_file_contexts -f "$GITHUB_WORKSPACE"/images/$i -a /$i "$GITHUB_WORKSPACE"/images/$i.img
                resize2fs -f -M "$GITHUB_WORKSPACE"/images/$i.img
                eval "$i"_size=$(du -sb "$GITHUB_WORKSPACE"/images/$i.img | awk {'print $1'})
                sudo rm -rf "$GITHUB_WORKSPACE"/images/$i
            done
            sudo rm -rf "$GITHUB_WORKSPACE"/images/TI_config
            for i in product system system_ext vendor
            do
                "$GITHUB_WORKSPACE"/tools/img2simg "$GITHUB_WORKSPACE"/images/$i.img "$GITHUB_WORKSPACE"/simages/$i.img
                rm -rf "$GITHUB_WORKSPACE"/images/$i.img
                python3 "$GITHUB_WORKSPACE"/tools/img2sdat.py "$GITHUB_WORKSPACE"/simages/$i.img -o "$GITHUB_WORKSPACE"/simages/ -v 4 -p $i
                rm -rf "$GITHUB_WORKSPACE"/simages/$i.img
                "$GITHUB_WORKSPACE"/tools/brotli -q 5 "$GITHUB_WORKSPACE"/simages/$i.new.dat -o "$GITHUB_WORKSPACE"/images/$i.new.dat.br
                mv "$GITHUB_WORKSPACE"/simages/$i.transfer.list "$GITHUB_WORKSPACE"/simages/$i.patch.dat "$GITHUB_WORKSPACE"/images
                rm -rf "$GITHUB_WORKSPACE"/simages/$i.new.dat
            done
            rm -rf "$GITHUB_WORKSPACE"/simages
            sed -i "s/product_size/$product_size/g" "$GITHUB_WORKSPACE"/images/dynamic_partitions_op_list
            sed -i "s/vendor_size/$vendor_size/g" "$GITHUB_WORKSPACE"/images/dynamic_partitions_op_list
            sed -i "s/system_size/$system_size/g" "$GITHUB_WORKSPACE"/images/dynamic_partitions_op_list
            sed -i "s/system_ext_size/$system_ext_size/g" "$GITHUB_WORKSPACE"/images/dynamic_partitions_op_list
            sudo 7z a "$GITHUB_WORKSPACE"/zip/miui_LMIPRE_$date.zip "$GITHUB_WORKSPACE"/images/*
            sudo rm -rf "$GITHUB_WORKSPACE"/images
            md5=$(md5sum "$GITHUB_WORKSPACE"/zip/miui_LMIPRE_$date.zip)
            zipmd5=${md5:0:10}
            mv "$GITHUB_WORKSPACE"/zip/miui_LMIPRE_$date.zip "$GITHUB_WORKSPACE"/zip/miui_LMIPRE_"$date"_$zipmd5.zip
            echo "artifact_name=miui_LMIPRE_"$date"_$zipmd5" >> $GITHUB_ENV
       - name: 6.上传到Artifact
         uses: actions/upload-artifact@v3
         with:
          name: ${{ env.artifact_name }}
          path: "./zip/*"
       - name: 7.删除工作流运行
         uses: Mattraks/delete-workflow-runs@v2
         with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
